// Auth
export const AUTHENTICATED = 'AUTHENTICATED'

// User
export const INITIALIZE_USERS = 'INITIALIZE_USERS'
export const CREATE_USER = 'CREATE_USER'

// Products
export const REQUEST_CURRENT_PRODUCT = 'REQUEST_CURRENT_PRODUCT'
export const RECEIVE_CURRENT_PRODUCT = 'RECEIVE_CURRENT_PRODUCT'
export const REQUEST_RELATED_PRODUCTS = 'REQUEST_RELATED_PRODUCTS'
export const RECEIVE_RELATED_PRODUCTS = 'RECEIVE_RELATED_PRODUCTS'
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

//Reviews
export const CREATE_REVIEW = 'CREATE_REVIEW'

// Cart
export const RECEIVE_CART_ITEM = 'RECEIVE_CART_ITEM'
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const DELETE_CART = 'DELETE_CART'
export const RECEIVE_CART = 'RECEIVE_CART'

//Checkout
export const SUBMIT_ORDER = 'SUBMIT_ORDER'
export const RETRIEVE_SUBMITTED_ORDER = 'RETRIEVE_SUBMITTED_ORDER'
